steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/rosy-rider-391913/cicd-teste', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/urosy-rider-391913/cicd-teste']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'minha-aplicacao'
      - '--image=gcr.io/rosy-rider-391913/cicd-teste'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
options:
  logging: NONE
